- name: Install java and the server.jar needed to run a Minecraft Server on a new Debian EC2 instance.
  hosts: all
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: apt update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
  
  - name: download java
    ansible.builtin.get_url:
      url: 'https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb'
      dest: '/home/admin'

  - name: install java
    become: true
    shell: dpkg -i /home/admin/jdk-21_linux-x64_bin.deb

  - name: install the minecraft server
    ansible.builtin.get_url:
      url: 'https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar'
      dest: '/home/admin'

  - name: run minecraft server startup
    shell: java -Xmx'{{xmx}}'M -Xms'{{xms}}'M -jar /home/admin/server.jar nogui
  
  - name: edit eula.txt
    shell: sed -i 's/false/true/g' /home/admin/eula.txt
  
  - name: get the IP and setup server.properties
    shell: sed -e "/server-ip=/c server-ip=$(hostname -I)" /home/admin/server.properties

  - name: create the mc service file
    copy:
      dest: '/home/admin/minecraftserver.service'
      content: |
        [Unit]
        Description=Minecraft Server

        [Service]
        Type=simple
        WorkingDirectory=/home/admin
        ExecStart=/usr/bin/java -Xmx'{{xmx}}'M -Xms'{{xms}}'M -jar server.jar nogui

        [Install]
        WantedBy=multi-user.target

  - name: cp the service file into systemd
    become: true
    shell: cp /home/admin/minecraftserver.service /etc/systemd/system/minecraftserver.service
  
  - name: chmod the service file
    become: true
    shell: chmod 644 /etc/systemd/system/minecraftserver.service

  - name: start the service
    become: true
    shell: systemctl daemon-reload; systemctl start minecraftserver

  - name: enable the service for future restarts
    become: true
    shell: systemctl enable minecraftserver
